// Elenco delle opzioni ricercabili
const OPT = [
  [
    "amm",
    "Situazione patrimoniale",
    "attivo, passivo, patrimonio netto e debito/valore del bene finanziato",
    {},
    "vb",
  ],
  [
    "amm",
    "Ammortamento francese",
    "mutuo a rata costante, quota capitale crescente",
    { t: "fr" },
  ],
  [
    "amm",
    "Ammortamento italiano",
    "quota capitale costante, rate decrescenti",
    { t: "it" },
  ],
  [
    "amm",
    "Ammortamento tedesco",
    "interessi anticipati, rata costante",
    { t: "de" },
  ],
  [
    "amm",
    "Ammortamento americano",
    "rimborso a scadenza, solo interessi",
    { t: "am", ric: "n" },
  ],
  [
    "amm",
    "Ammortamento americano con rata costitutiva",
    "fondo di ricostituzione del capitale, rata costitutiva",
    { t: "am", ric: "s" },
    "rr",
  ],
  [
    "amm",
    "Rata costitutiva",
    "prospetto di costituzione del capitale, fondo di ammortamento",
    { t: "am", ric: "s" },
    "rr",
  ],
  ["amm", "Rate mensili", "piano di ammortamento mensile", { m: 12 }, "m"],
  [
    "amm",
    "Rate trimestrali",
    "piano di ammortamento trimestrale",
    { m: 4 },
    "m",
  ],
  ["pre", "Prestito personale", "rata, interessi totali, TAEG"],
  ["pre", "TAEG", "spese di istruttoria e di incasso", {}, "e"],
  [
    "pre",
    "Sostenibilità della rata",
    "rata entro un terzo del reddito netto",
    {},
    "w",
  ],
  [
    "pre",
    "Prestito a tasso variabile",
    "nuova rata dopo variazione del tasso",
    {},
    "r2",
  ],
  [
    "val",
    "Valore attuale di una somma",
    "attualizzazione, sconto composto",
    { m: "s" },
    "C",
  ],
  [
    "val",
    "Montante di una somma",
    "capitalizzazione composta",
    { m: "s" },
    "C",
  ],
  [
    "val",
    "Rendita posticipata a rata costante",
    "valore attuale e montante",
    { m: "c", p: "p" },
  ],
  [
    "val",
    "Rendita anticipata a rata costante",
    "valore attuale e montante",
    { m: "c", p: "a" },
  ],
  [
    "val",
    "Rendita a rate variabili posticipata",
    "valore attuale e montante",
    { m: "v", p: "p" },
    "fl",
  ],
  [
    "val",
    "Rendita a rate variabili anticipata",
    "valore attuale e montante",
    { m: "v", p: "a" },
    "fl",
  ],
  [
    "con",
    "Tasso continuo da tasso effettivo",
    "δ = ln(1+i), intensità istantanea",
    { d: "i" },
  ],
  ["con", "Tasso effettivo da intensità δ", "i = e^δ − 1", { d: "d" }],
  [
    "dur",
    "Duration di un’obbligazione",
    "Macaulay e modificata, durata media finanziaria",
  ],
  ["dur", "Convessità", "correzione del secondo ordine"],
  ["dur", "Cedole mensili", "12 cedole all’anno", { p: 12, pu: "f" }, "p"],
  ["dur", "Cedole semestrali", "2 cedole all’anno", { p: 2, pu: "f" }, "p"],
  ["dur", "Cedole annuali", "1 cedola all’anno", { p: 1, pu: "f" }, "p"],
  ["dur", "Variazione del prezzo per Δr", "ΔP ≈ −D·P·Δr/(1+r)", {}, "dr"],
  ["flu", "Duration di un flusso", "importi e scadenze libere"],
  ["flu", "Scadenza media aritmetica", "senza tasso di interesse", {}, "fl"],
  ["flu", "Duration al tempo t*", "tempo di valutazione", {}, "tx"],
  ["vc", "Varianza", "varianza campionaria e di popolazione", {}, "x"],
  ["vc", "Covarianza", "covarianza tra due serie", {}, "x"],
  ["vc", "Correlazione", "coefficiente di correlazione ρ", {}, "x"],
  ["vc", "Retta di regressione", "minimi quadrati, R²", {}, "x"],
  ["vc", "Deviazione standard", "scarto quadratico medio", {}, "x"],
  [
    "vc",
    "Varianza di portafoglio",
    "due titoli, peso a varianza minima",
    {},
    "w",
  ],
  [
    "tas",
    "Tassi equivalenti",
    "tasso effettivo, nominale convertibile, sconto",
  ],
  [
    "tas",
    "Tasso nominale convertibile",
    "j(m), frazionamento",
    { d: "j" },
    "x",
  ],
  ["tas", "Tasso di sconto", "d = i/(1+i), anticipato", { d: "d" }, "x"],
  ["reg", "Interesse semplice", "regime semplice, montante"],
  [
    "reg",
    "Sconto commerciale",
    "sconto razionale, commerciale, composto",
    {},
    "d",
  ],
  [
    "obb",
    "Prezzo di un’obbligazione",
    "prezzo dal rendimento, cedole",
    { m: "p" },
  ],
  [
    "obb",
    "Rendimento a scadenza YTM",
    "rendimento dal prezzo, current yield",
    { m: "y" },
    "P",
  ],
  ["obb", "Zero coupon", "obbligazione senza cedola", { c: 0 }, "c"],
  [
    "pac",
    "Piano di accumulo",
    "PAC, montante di versamenti periodici",
    { m: "m" },
  ],
  [
    "pac",
    "Versamento per un obiettivo",
    "rata necessaria per raggiungere un capitale",
    { m: "r" },
    "G",
  ],
  [
    "pac",
    "Tempo per raggiungere un obiettivo",
    "quanti anni servono",
    { m: "t" },
    "G",
  ],
  ["ren", "Rendita perpetua", "valore attuale illimitato", { m: "p" }],
  [
    "ren",
    "Formula di Gordon",
    "perpetua crescente, dividendi",
    { m: "c" },
    "g",
  ],
  [
    "ren",
    "Rendita differita",
    "pagamenti che partono dopo s periodi",
    { m: "d" },
    "s",
  ],
  [
    "ren",
    "Rendita crescente aritmetica",
    "rate in progressione aritmetica",
    { m: "a" },
    "D",
  ],
  [
    "ren",
    "Rendita crescente geometrica",
    "rate in progressione geometrica",
    { m: "g" },
    "g",
  ],
  ["inf", "Tasso reale di Fisher", "inflazione, potere d’acquisto", {}, "p"],
  ["inf", "Imposta sugli interessi", "rendimento netto, tassazione", {}, "tau"],
  ["cap", "CAPM", "rendimento atteso, security market line", {}, "beta"],
  ["cap", "Indice di Sharpe", "rendimento corretto per il rischio", {}, "sp"],
  ["cap", "Alpha di Jensen", "extra-rendimento, Treynor", {}, "rp"],
  [
    "cap",
    "Beta da serie storiche",
    "covarianza con il mercato / varianza",
    {},
    "a",
  ],
  [
    "rnd",
    "Volatilità storica",
    "rendimenti da prezzi, deviazione standard",
    {},
    "pr",
  ],
  ["rnd", "Massimo drawdown", "perdita massima dal picco", {}, "pr"],
  ["rnd", "CAGR", "rendimento annuo composto", {}, "pr"],
  ["rnd", "Value at Risk", "VaR parametrico", {}, "z"],
  ["opz", "Opzione call", "Black-Scholes, prezzo call"],
  ["opz", "Opzione put", "Black-Scholes, prezzo put"],
  ["opz", "Greche", "delta, gamma, vega, theta, rho", {}, "s"],
  ["npv", "Indice di profitabilità", "payback scontato", {}, "fl"],
  ["npv", "VAN", "valore attuale netto, NPV", {}, "r"],
  ["npv", "TIR", "tasso interno di rendimento, IRR", {}, "fl"],
  [
    "sp",
    "Patrimonio netto",
    "attivo, passivo, debito/valore del bene con mutuo",
    {},
    "vb",
  ],
  [
    "pat",
    "Tasso patrimoniale",
    "crescita annua composta del patrimonio, CAGR",
    {},
    "w0",
  ],
  [
    "pat",
    "Patrimonio obiettivo",
    "anni per raggiungere un capitale target",
    {},
    "g",
  ],
  ["tay", "Maclaurin", "sviluppo di Taylor centrato in 0", {}, "a"],
  [
    "imm",
    "Redington",
    "immunizzazione, duration e convessità dell'attivo",
    {},
    "H",
  ],
  [
    "cv",
    "Convertitore valute",
    "cambio EUR USD GBP, bandiera e valuta della nazione",
    {},
    "p1",
  ],
];
